export const config = {
  app: {
    width: 720,
    height: 1280,
    background: 0x0b1020,
    preference: "webgl",
    antialias: false,
  },
  game: {
    debug: true,
  },
  world: {
    gravityX: 0,
    gravityY: -10,
    timeStep: 1 / 60,
    velocityIterations: 6,
    positionIterations: 2,
    maxSubSteps: 5,
    pixelsPerMeter: 40,
    originX: 0,
    originY: 1280,
  },
  box: {
    density: 1,
    staticDensity: 0,
    friction: 0.45,
    restitution: 0.05,
    margin: 0.15,
  },
  level: {
    wallThickness: 0.8,
    wallColor: 0x3d4a5c,
  },
  particles: {
    radius: 0.15,
    damping: 0.7,
    density: 1.2,
    viscous: false,
    tensile: false,
    colorMixing: true,
    colorMixingStrength: 0.5,
    maxCount: 8192,
    textureSize: 32,
    scale: 1,
    anchor: 0.5,
    gradientInner: "rgba(255,255,255,1)",
    gradientOuter: "rgba(255,255,255,0)",
    blendMode: "normal",
    offscreenX: -4096,
    offscreenY: -4096,
  },
  metaball: {
    threshold: 0.42,
    softness: 0.08,
    stroke: 0.16,
    fillAlpha: 0.78,
    padding: 0,
  },
  faucet: {
    hx: 0.22,
    hy: 0.45,
    rate: 40,
    speed: 6,
  },
  flask: {
    innerWidth: 4.2,
    innerHeight: 5.2,
    thickness: 0.4,
    color: 0x8a9bb0,
    liquidColor: [120, 190, 255, 255],
  },
  debug: {
    hudFill: 0xffffff,
    hudFontSize: 16,
    hudX: 12,
    hudY: 12,
    msDigits: 2,
    fpsDigits: 0,
    lineWidth: 1,
    particleDot: 2,
    staticColor: 0x80ff80,
    kinematicColor: 0x8080ff,
    dynamicColor: 0xff80ff,
    particleColor: 0x88ccff,
  },
};
